### ISSUE TITLE
Allegro esta sendo utilizada sem necessariamente estar instalada

### ISSUE THREAD

**Issue by tcanabrava** [lucasew/allegro_blasteroids#1]
https://github.com/lucasew/allegro_blasteroids/blob/893fc287ff68abdfeb2a720348e6ed43f2725126/CMakeLists.txt#L4

Utilize o CMake junto com o find_package(Allegro REQUIRED), podendo tambem especificar a versao.
O allegro nao faz parte do padrao de pacotes do CMake, mas voce pode pegar um script de find em https://github.com/DFHack/stonesense/blob/master/CMake/Modules/FindAllegro.cmake

Isso faz com que o cmake avise caso o allegro nao exista nos computadores de quem esta tentando.

**Comment by lucasew** [comment]
Eu coloquei ele para checar pela  header do Allegro, se achar o teste passa, senão ele abandona e dá erro. Obrigado.
