### ISSUE TITLE
Evite add_executable com muitos arquivos fonte

### ISSUE THREAD

**Issue by tcanabrava** [lucasew/allegro_blasteroids#2]
https://github.com/lucasew/allegro_blasteroids/blob/893fc287ff68abdfeb2a720348e6ed43f2725126/CMakeLists.txt#L4
use o add_library(blasteroids_core STATIC arquivos do core)  pra que voce consiga dividir o codigo em modulos que serao depois linkados no programa final.

**Comment by lucasew** [comment]
Separei em core, utils e o main que linka as duas. Acho que está resolvido.
