### ISSUE TITLE
Blasteroids na verdade se chama 'game'

### ISSUE THREAD

**Issue by tcanabrava** [lucasew/allegro_blasteroids#4]
https://github.com/lucasew/allegro_blasteroids/blob/893fc287ff68abdfeb2a720348e6ed43f2725126/CMakeLists.txt#L7

O nome do executavel eh o nome final do binario do seu jogo, logo nao deve se chamar 'game'. blasteroids seria um nome melhor.

**Comment by lucasew** [comment]
Resolvido, agora o executável é blasteroids ao invés de game.
