### ISSUE TITLE
Nao use malloc pra boolean

### ISSUE THREAD

**Issue by tcanabrava** [lucasew/allegro_blasteroids#5]
https://github.com/lucasew/allegro_blasteroids/blob/893fc287ff68abdfeb2a720348e6ed43f2725126/main.c#L27

Isso eh estilo java de programacao, boolean nao deve ser criado com malloc, nao faz sentido ter algo que eh menor do que um ponteiro ter uma entrada no heap.

**Comment by lucasew** [comment]
Resolvido
