### ISSUE TITLE
Nao usar malloc pra tudo.

### ISSUE THREAD

**Issue by tcanabrava** [lucasew/allegro_blasteroids#6]
https://github.com/lucasew/allegro_blasteroids/blob/893fc287ff68abdfeb2a720348e6ed43f2725126/main.c#L33

Novamente malloc - voce nao precisa de malloc pra tudo, isso eh costume de linguagens como java. Malloc deixa teu codigo mais lento, a memoria do malloc eh uma memoria mais lenta de acessar que a memoria de pilha. voce so deve deixar no heap coisas que realmente tem que ir pra o heap.

**Comment by lucasew** [comment]
Resolvido
