### ISSUE TITLE
crie funcoes construtoras para esse tipo de acao.

### ISSUE THREAD

**Issue by tcanabrava** [lucasew/allegro_blasteroids#7]
https://github.com/lucasew/allegro_blasteroids/blob/893fc287ff68abdfeb2a720348e6ed43f2725126/main.c#L74

Funcoes construtoras criam e inicializam os valores dos seus elementos, e retornam o valor criado Como voce esta fazendo todo o codigo fica muito espalhado e fica dificil de seguir. Alem disso, nao precisa de malloc.

**Comment by lucasew** [comment]
Já dei uma organizada no código e essa linha por exemplo já não se faz mais necessária. Resolvido.
